services:
  - type: web
    name: classroom-emotions-analyzer
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - "*.py"
        - "requirements.txt"
        - "templates/**"
        - "static/**"
        - "*.yaml"
        - "*.yml"
